# Generated by Django 3.2.5 on 2021-10-31 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_webpage', models.URLField(blank=True)),
                ('user_facebook_link', models.URLField(blank=True)),
                ('user_instagram_link', models.URLField(blank=True)),
                ('user_presentation', models.TextField()),
                ('user_birthdate', models.DateField(blank=True)),
                ('user_unmarried_lname', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=240)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('body', models.TextField()),
                ('meta_description', models.CharField(blank=True, max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fblog_app.userprofile')),
                ('tags', models.ManyToManyField(blank=True, to='fblog_app.Tag')),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_description', models.CharField(blank=True, max_length=250)),
                ('group_presentation', models.TextField()),
                ('group_ext_url', models.URLField(blank=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
            ],
        ),
    ]
